"""
Vector Database Service (Qdrant)

Qdrant is a high-performance vector database built for AI applications.
It stores and searches 1024-dimensional embeddings generated by DINOv2.

WHAT IS A VECTOR DATABASE?

Traditional databases (PostgreSQL) store structured data — strings, numbers, dates.
They search by exact match or range queries: WHERE type = 'flowchart'.

Vector databases store EMBEDDINGS — dense float arrays that encode MEANING.
They search by SIMILARITY: "find diagrams whose meaning is closest to this one."

HOW SIMILARITY SEARCH WORKS:

1. Each diagram gets an embedding: [0.12, -0.34, 0.87, ...] (1024 numbers)
2. These embeddings live in 1024-dimensional space
3. Similar diagrams cluster together in this space
4. "Search" = find the nearest embeddings to your query embedding

DISTANCE METRICS:
- Cosine similarity: angle between vectors (works well for normalized embeddings)
  - 1.0 = identical, 0.0 = completely different, -1.0 = opposite
- Euclidean distance: straight-line distance (good for absolute values)
- Dot product: product of magnitudes (fast, used in retrieval)

We use COSINE because our DINOv2 embeddings are L2-normalized.

WHY QDRANT OVER ALTERNATIVES?
| Database     | Speed    | Features       | Deployment  |
|--------------|----------|----------------|-------------|
| Qdrant       | Very fast| Rich filtering | Docker/Cloud|
| Pinecone     | Fast     | Managed only   | Cloud only  |
| ChromaDB     | Medium   | Simple API     | In-memory   |
| FAISS        | Very fast| No metadata    | In-process  |
| Weaviate     | Fast     | GraphQL API    | Complex     |

Qdrant chosen because: fast, can filter by metadata, runs locally in Docker,
open source, production-ready.

NEAREST NEIGHBOR SEARCH (HNSW Algorithm):
Qdrant uses HNSW (Hierarchical Navigable Small World graphs):
- Building an index that connects similar vectors with edges
- Search navigates the graph: start at entry point, greedily move to closer nodes
- O(log N) search complexity → millions of vectors, millisecond search
"""
import uuid
import numpy as np
import logging
from typing import List, Dict, Optional, Any

log = logging.getLogger(__name__)


class VectorService:
    """
    Manages all vector embedding storage and similarity search in Qdrant.
    
    Operations:
    - store_embedding(): Save a diagram's embedding + metadata
    - search_similar(): Find the N most similar diagrams
    - delete_embedding(): Remove a diagram's embedding
    - get_by_id(): Retrieve a specific embedding by ID
    """
    
    # DINOv2-small produces 384-dim embeddings; DINOv2-large → 1024-dim.
    # We default to 384 to match the dinov2-small model configured in .env.
    EMBEDDING_DIM = 384

    def __init__(self):
        self._client = None
        self._collection_ready = False

    def _get_client(self):
        """Lazy-load Qdrant client and ensure collection exists with correct dims."""
        if self._client:
            return self._client
        try:
            from qdrant_client import QdrantClient
            from qdrant_client.models import VectorParams, Distance
            from core.config import settings
            self._client = QdrantClient(
                host=settings.QDRANT_HOST,
                port=settings.QDRANT_PORT,
                timeout=10
            )
            # Ensure the collection exists with the correct vector dimension
            col_name = self._get_collection_name()
            existing = [c.name for c in self._client.get_collections().collections]
            if col_name not in existing:
                self._client.create_collection(
                    collection_name=col_name,
                    vectors_config=VectorParams(
                        size=self.EMBEDDING_DIM,
                        distance=Distance.COSINE
                    ),
                )
                log.info(f"✅ Created Qdrant collection '{col_name}' with dim={self.EMBEDDING_DIM}")
            else:
                # Verify the existing collection has the right dimension
                info = self._client.get_collection(col_name)
                existing_dim = info.config.params.vectors.size
                if existing_dim != self.EMBEDDING_DIM:
                    log.warning(
                        f"⚠️  Qdrant collection '{col_name}' has dim={existing_dim} "
                        f"but we need dim={self.EMBEDDING_DIM}. Recreating..."
                    )
                    self._client.delete_collection(col_name)
                    self._client.create_collection(
                        collection_name=col_name,
                        vectors_config=VectorParams(
                            size=self.EMBEDDING_DIM,
                            distance=Distance.COSINE
                        ),
                    )
                    log.info(f"✅ Recreated Qdrant collection '{col_name}' with dim={self.EMBEDDING_DIM}")
        except Exception as e:
            log.warning(f"⚠️  Qdrant not available: {e}")
        return self._client

    def store_embedding(
        self,
        upload_id: str,
        embedding: np.ndarray,
        metadata: Dict[str, Any],
    ) -> str:
        """
        Store a diagram embedding in Qdrant, with a fallback to PostgreSQL pgvector.
        """
        # Ensure point_id is a valid UUID or integer for Qdrant
        try:
            point_id = str(uuid.UUID(upload_id))
        except ValueError:
            # Deterministic UUID fallback
            point_id = str(uuid.uuid5(uuid.NAMESPACE_DNS, upload_id))

        qdrant_success = False
        client = self._get_client()
        if client:
            try:
                from qdrant_client.models import PointStruct
                
                vector = embedding.tolist()
                point = PointStruct(
                    id=point_id,
                    vector=vector,
                    payload={
                        **metadata,
                        "embedding_dim": len(vector),
                    }
                )
                client.upsert(
                    collection_name=self._get_collection_name(),
                    points=[point],
                    wait=True
                )
                log.info(f"📦 Stored embedding in Qdrant for upload {upload_id[:8]}...")
                qdrant_success = True
            except Exception as e:
                log.warning(f"⚠️  Qdrant store failed: {e}. Falling back to pgvector...")
        
        # Always store in PostgreSQL as primary/fallback record
        try:
            from sqlalchemy import create_engine, text
            from core.config import settings
            
            sync_url = settings.DATABASE_URL.replace("postgresql+asyncpg://", "postgresql://")
            sync_engine = create_engine(sync_url)
            vector_str = "[" + ",".join(map(str, embedding.tolist())) + "]"
            
            with sync_engine.begin() as conn:
                try:
                    conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector;"))
                except Exception:
                    pass  # Might not have superuser privileges, ignore
                
                sql = text("""
                    UPDATE diagram_uploads
                    SET embedding_vector = :vector_str,
                        diagram_type = :diagram_type,
                        ocr_text = :ocr_text
                    WHERE id = :upload_id;
                """)
                conn.execute(sql, {
                    "vector_str": vector_str,
                    "diagram_type": metadata.get("diagram_type", "unknown"),
                    "ocr_text": metadata.get("ocr_text", ""),
                    "upload_id": upload_id
                })
                log.info(f"💾 Stored embedding in PostgreSQL for upload {upload_id[:8]}...")
        except Exception as e:
            log.error(f"❌ PostgreSQL store embedding error: {e}")
            
        return upload_id

    def search_similar(
        self,
        query_embedding: np.ndarray,
        limit: int = 5,
        filters: Optional[Dict] = None,
        score_threshold: float = 0.3,
    ) -> List[Dict]:
        """
        Find the N most similar diagrams, checking Qdrant first, and pgvector as fallback.
        """
        client = self._get_client()
        if client:
            try:
                from qdrant_client.models import Filter, FieldCondition, MatchValue, QueryRequest
                
                qdrant_filter = None
                if filters:
                    conditions = [
                        FieldCondition(key=k, match=MatchValue(value=v))
                        for k, v in filters.items()
                    ]
                    qdrant_filter = Filter(must=conditions)
                
                # qdrant-client ≥1.7: use query_points() instead of deprecated search()
                response = client.query_points(
                    collection_name=self._get_collection_name(),
                    query=query_embedding.tolist(),
                    limit=limit,
                    query_filter=qdrant_filter,
                    score_threshold=score_threshold,
                    with_payload=True,
                    with_vectors=False,
                )
                hits = response.points
                
                formatted = [
                    {
                        "id": str(hit.id),
                        "score": float(hit.score),
                        "diagram_type": hit.payload.get("diagram_type", "unknown"),
                        "ocr_text": hit.payload.get("ocr_text", ""),
                        "explanation": hit.payload.get("explanation", ""),
                        "file_path": hit.payload.get("file_path", ""),
                        "session_id": hit.payload.get("session_id", ""),
                    }
                    for hit in hits
                ]
                
                log.info(f"🔍 Found {len(formatted)} similar diagrams in Qdrant")
                return formatted
            except Exception as e:
                log.warning(f"⚠️  Qdrant search failed: {e}. Falling back to pgvector...")
        
        # Fallback to pgvector search in PostgreSQL
        try:
            from sqlalchemy import create_engine, text
            from core.config import settings
            
            sync_url = settings.DATABASE_URL.replace("postgresql+asyncpg://", "postgresql://")
            sync_engine = create_engine(sync_url)
            query_vector_str = "[" + ",".join(map(str, query_embedding.tolist())) + "]"
            
            with sync_engine.connect() as conn:
                sql = text("""
                    SELECT id, diagram_type, ocr_text, file_path, session_id,
                           (1.0 - (CAST(embedding_vector AS vector) <=> CAST(:query_vector AS vector))) as similarity
                    FROM diagram_uploads
                    WHERE embedding_vector IS NOT NULL
                    ORDER BY CAST(embedding_vector AS vector) <=> CAST(:query_vector AS vector) ASC
                    LIMIT :limit;
                """)
                res = conn.execute(sql, {"query_vector": query_vector_str, "limit": limit})
                
                formatted = []
                for row in res:
                    similarity = float(row[5])
                    if similarity >= score_threshold:
                        formatted.append({
                            "id": str(row[0]),
                            "score": similarity,
                            "diagram_type": row[1] or "unknown",
                            "ocr_text": row[2] or "",
                            "explanation": "Retrieved via pgvector similarity search.",
                            "file_path": row[3] or "",
                            "session_id": str(row[4]) if row[4] else "",
                        })
                log.info(f"🔍 Found {len(formatted)} similar diagrams in PostgreSQL pgvector")
                return formatted
        except Exception as pg_err:
            log.error(f"❌ PostgreSQL pgvector search error: {pg_err}")
            return []

    def search_by_text(self, text_query: str, limit: int = 5) -> List[Dict]:
        """
        Search diagrams by text content (keyword-based, not semantic).
        
        Qdrant supports full-text search on payload fields.
        Useful for searching by OCR text: "find diagrams mentioning 'binary search'"
        
        For TRUE semantic text search, you'd embed the text query
        using CLIP or a text encoder and search the vector space.
        """
        client = self._get_client()
        if not client:
            return []
        
        try:
            from qdrant_client.models import Filter, FieldCondition, MatchText
            
            # Qdrant full-text search on 'ocr_text' payload field
            results = client.scroll(
                collection_name=self._get_collection_name(),
                scroll_filter=Filter(
                    must=[
                        FieldCondition(
                            key="ocr_text",
                            match=MatchText(text=text_query)
                        )
                    ]
                ),
                limit=limit,
                with_payload=True,
            )[0]
            
            return [
                {
                    "id": str(r.id),
                    "score": 1.0,  # Text match = full score
                    "diagram_type": r.payload.get("diagram_type", "unknown"),
                    "ocr_text": r.payload.get("ocr_text", ""),
                    "explanation": r.payload.get("explanation", ""),
                }
                for r in results
            ]
            
        except Exception as e:
            log.error(f"Text search error: {e}")
            return []

    def delete_embedding(self, upload_id: str) -> bool:
        """Remove a specific embedding from Qdrant."""
        client = self._get_client()
        if not client:
            return False
        
        try:
            from qdrant_client.models import PointIdsList
            client.delete(
                collection_name=self._get_collection_name(),
                points_selector=PointIdsList(points=[upload_id]),
            )
            return True
        except Exception as e:
            log.error(f"Delete error: {e}")
            return False

    def get_collection_stats(self) -> Dict:
        """Get statistics about the Qdrant collection."""
        client = self._get_client()
        if not client:
            return {"available": False}
        
        try:
            from core.config import settings
            info = client.get_collection(settings.QDRANT_COLLECTION)
            return {
                "available": True,
                "total_vectors": info.points_count,
                "indexed_vectors": info.indexed_vectors_count,
                "status": str(info.status),
            }
        except Exception as e:
            return {"available": False, "error": str(e)}

    def _get_collection_name(self) -> str:
        from core.config import settings
        return settings.QDRANT_COLLECTION


# Singleton
vector_service = VectorService()
