"""
Vector Database Service (Qdrant)

Qdrant is a high-performance vector database built for AI applications.
It stores and searches 1024-dimensional embeddings generated by DINOv2.

WHAT IS A VECTOR DATABASE?

Traditional databases (PostgreSQL) store structured data — strings, numbers, dates.
They search by exact match or range queries: WHERE type = 'flowchart'.

Vector databases store EMBEDDINGS — dense float arrays that encode MEANING.
They search by SIMILARITY: "find diagrams whose meaning is closest to this one."

HOW SIMILARITY SEARCH WORKS:

1. Each diagram gets an embedding: [0.12, -0.34, 0.87, ...] (1024 numbers)
2. These embeddings live in 1024-dimensional space
3. Similar diagrams cluster together in this space
4. "Search" = find the nearest embeddings to your query embedding

DISTANCE METRICS:
- Cosine similarity: angle between vectors (works well for normalized embeddings)
  - 1.0 = identical, 0.0 = completely different, -1.0 = opposite
- Euclidean distance: straight-line distance (good for absolute values)
- Dot product: product of magnitudes (fast, used in retrieval)

We use COSINE because our DINOv2 embeddings are L2-normalized.

WHY QDRANT OVER ALTERNATIVES?
| Database     | Speed    | Features       | Deployment  |
|--------------|----------|----------------|-------------|
| Qdrant       | Very fast| Rich filtering | Docker/Cloud|
| Pinecone     | Fast     | Managed only   | Cloud only  |
| ChromaDB     | Medium   | Simple API     | In-memory   |
| FAISS        | Very fast| No metadata    | In-process  |
| Weaviate     | Fast     | GraphQL API    | Complex     |

Qdrant chosen because: fast, can filter by metadata, runs locally in Docker,
open source, production-ready.

NEAREST NEIGHBOR SEARCH (HNSW Algorithm):
Qdrant uses HNSW (Hierarchical Navigable Small World graphs):
- Building an index that connects similar vectors with edges
- Search navigates the graph: start at entry point, greedily move to closer nodes
- O(log N) search complexity → millions of vectors, millisecond search
"""
import uuid
import numpy as np
import logging
from typing import List, Dict, Optional, Any

log = logging.getLogger(__name__)


class VectorService:
    """
    Manages all vector embedding storage and similarity search in Qdrant.
    
    Operations:
    - store_embedding(): Save a diagram's embedding + metadata
    - search_similar(): Find the N most similar diagrams
    - delete_embedding(): Remove a diagram's embedding
    - get_by_id(): Retrieve a specific embedding by ID
    """
    
    def __init__(self):
        self._client = None

    def _get_client(self):
        """Lazy-load Qdrant client."""
        if self._client:
            return self._client
        try:
            from qdrant_client import QdrantClient
            from core.config import settings
            self._client = QdrantClient(
                host=settings.QDRANT_HOST,
                port=settings.QDRANT_PORT,
                timeout=10
            )
        except Exception as e:
            log.warning(f"⚠️  Qdrant not available: {e}")
        return self._client

    def store_embedding(
        self,
        upload_id: str,
        embedding: np.ndarray,
        metadata: Dict[str, Any],
    ) -> str:
        """
        Store a diagram embedding in Qdrant.
        
        Each Qdrant "point" contains:
        - id: unique identifier (we use upload_id)
        - vector: the 1024-dim float array from DINOv2
        - payload: metadata dict (searchable + filterable)
        
        PAYLOAD FIELDS WE STORE:
        - diagram_type: "flowchart", "dsa", "architecture", etc.
        - ocr_text: extracted text content
        - session_id: which session this belongs to
        - user_id: owner
        - explanation: AI-generated explanation
        - file_path: where the image is stored
        - created_at: timestamp
        
        This allows hybrid search: vector similarity + metadata filters
        Example: "Find similar flowcharts FROM THIS USER created AFTER last week"
        
        Args:
            upload_id: UUID of the upload record in PostgreSQL
            embedding: 1024-dim numpy array from DINOv2
            metadata: dict of searchable metadata
            
        Returns:
            The Qdrant point ID (same as upload_id)
        """
        client = self._get_client()
        if not client:
            log.warning("Qdrant unavailable — skipping embedding storage")
            return upload_id
        
        try:
            from qdrant_client.models import PointStruct
            from core.config import settings
            
            # Convert to plain Python list (Qdrant doesn't accept numpy)
            vector = embedding.tolist()
            
            # Create the point
            point = PointStruct(
                id=upload_id,  # Use upload_id as Qdrant point ID
                vector=vector,
                payload={
                    **metadata,
                    "embedding_dim": len(vector),
                }
            )
            
            # Upsert (insert or update if already exists)
            client.upsert(
                collection_name=self._get_collection_name(),
                points=[point],
                wait=True  # Wait for indexing to complete
            )
            
            log.info(f"📦 Stored embedding for upload {upload_id[:8]}...")
            return upload_id
            
        except Exception as e:
            log.error(f"❌ Qdrant storage error: {e}")
            return upload_id

    def search_similar(
        self,
        query_embedding: np.ndarray,
        limit: int = 5,
        filters: Optional[Dict] = None,
        score_threshold: float = 0.3,
    ) -> List[Dict]:
        """
        Find the N most similar diagrams to a query embedding.
        
        HOW THE SEARCH WORKS:
        1. query_embedding: 1024-dim vector of the new diagram
        2. Qdrant computes cosine similarity against ALL stored embeddings
        3. Uses HNSW index to find approximate nearest neighbors (fast!)
        4. Returns top N results with similarity scores
        
        FILTERING:
        Qdrant supports filtering by payload fields DURING vector search.
        This is called "filtered vector search" or "hybrid search."
        
        Example filter: "Only search diagrams of type 'flowchart'"
        {
            "must": [
                {"key": "diagram_type", "match": {"value": "flowchart"}}
            ]
        }
        
        Args:
            query_embedding: 1024-dim query vector
            limit: max results to return
            filters: Qdrant filter dict (optional)
            score_threshold: minimum similarity score (0-1)
            
        Returns:
            List of dicts: [{id, score, payload}, ...]
        """
        client = self._get_client()
        if not client:
            return []
        
        try:
            from qdrant_client.models import Filter, FieldCondition, MatchValue
            
            qdrant_filter = None
            if filters:
                conditions = []
                for key, value in filters.items():
                    conditions.append(
                        FieldCondition(key=key, match=MatchValue(value=value))
                    )
                qdrant_filter = Filter(must=conditions)
            
            results = client.search(
                collection_name=self._get_collection_name(),
                query_vector=query_embedding.tolist(),
                limit=limit,
                query_filter=qdrant_filter,
                score_threshold=score_threshold,
                with_payload=True,   # Return metadata with results
                with_vectors=False,  # Don't return raw vectors (save bandwidth)
            )
            
            formatted = []
            for hit in results:
                formatted.append({
                    "id": str(hit.id),
                    "score": float(hit.score),
                    "diagram_type": hit.payload.get("diagram_type", "unknown"),
                    "ocr_text": hit.payload.get("ocr_text", ""),
                    "explanation": hit.payload.get("explanation", ""),
                    "file_path": hit.payload.get("file_path", ""),
                    "session_id": hit.payload.get("session_id", ""),
                })
            
            log.info(f"🔍 Found {len(formatted)} similar diagrams")
            return formatted
            
        except Exception as e:
            log.error(f"❌ Qdrant search error: {e}")
            return []

    def search_by_text(self, text_query: str, limit: int = 5) -> List[Dict]:
        """
        Search diagrams by text content (keyword-based, not semantic).
        
        Qdrant supports full-text search on payload fields.
        Useful for searching by OCR text: "find diagrams mentioning 'binary search'"
        
        For TRUE semantic text search, you'd embed the text query
        using CLIP or a text encoder and search the vector space.
        """
        client = self._get_client()
        if not client:
            return []
        
        try:
            from qdrant_client.models import Filter, FieldCondition, MatchText
            
            # Qdrant full-text search on 'ocr_text' payload field
            results = client.scroll(
                collection_name=self._get_collection_name(),
                scroll_filter=Filter(
                    must=[
                        FieldCondition(
                            key="ocr_text",
                            match=MatchText(text=text_query)
                        )
                    ]
                ),
                limit=limit,
                with_payload=True,
            )[0]
            
            return [
                {
                    "id": str(r.id),
                    "score": 1.0,  # Text match = full score
                    "diagram_type": r.payload.get("diagram_type", "unknown"),
                    "ocr_text": r.payload.get("ocr_text", ""),
                    "explanation": r.payload.get("explanation", ""),
                }
                for r in results
            ]
            
        except Exception as e:
            log.error(f"Text search error: {e}")
            return []

    def delete_embedding(self, upload_id: str) -> bool:
        """Remove a specific embedding from Qdrant."""
        client = self._get_client()
        if not client:
            return False
        
        try:
            from qdrant_client.models import PointIdsList
            client.delete(
                collection_name=self._get_collection_name(),
                points_selector=PointIdsList(points=[upload_id]),
            )
            return True
        except Exception as e:
            log.error(f"Delete error: {e}")
            return False

    def get_collection_stats(self) -> Dict:
        """Get statistics about the Qdrant collection."""
        client = self._get_client()
        if not client:
            return {"available": False}
        
        try:
            from core.config import settings
            info = client.get_collection(settings.QDRANT_COLLECTION)
            return {
                "available": True,
                "total_vectors": info.points_count,
                "indexed_vectors": info.indexed_vectors_count,
                "status": str(info.status),
            }
        except Exception as e:
            return {"available": False, "error": str(e)}

    def _get_collection_name(self) -> str:
        from core.config import settings
        return settings.QDRANT_COLLECTION


# Singleton
vector_service = VectorService()
